#!/bin/bash


sudo apt-get update
sudo apt-get install nginx
sudo apt-get install php php-fpm php-mysql
sudo apt-get install mysql-server

cat <<EOF >/etc/nginx/sites-enabled/default
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
         location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        }
        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files \$uri \$uri/ =404;
#       }
#}
EOF

rm /var/www/html/*
service nginx reload
cat <<EOF > /var/www/html/index.php
<?php
session_start();
\$flag = "CYBERHUB{50m3_ppl_H4te_SQLi_wbu_my_Fr!nD}";
?>
<!DOCTYPE html>
<html>
        <head>
	                <title>Home</title>
        </head>
        <body style="background-color: black;color:green;">
	                <center>
			                <h2><a href="login.php">login</a></h2>
                <?php
                        if(@\$_SESSION['flag'] == 1 ){
                                if( @\$_SESSION['admin'] == 1 ){
                                        echo "<center><h1><font color='green'>".\$flag."</font></h1></center>";
                                }else{
                                        echo "<center><h1>Welcome User.</h1></center>";
                                }
                        }
                ?>
                </center>
        </body>
</html>
EOF

cat <<EOF > /var/www/html/login.php
<?php

session_start();
if( \$_SERVER['REQUEST_METHOD'] == "POST" ){
        \$uname = @\$_POST['uname'];
        \$passwd = @\$_POST['passwd'];
	        if( strpos(\$uname, " ") ){
			                echo "<center><h1>I hate Hackers <span style='font-size:100px;'>&#129324;</span></h1></center>";
                die();
        }
        \$conn = mysqli_connect("localhost", "user", "password", "cyhub");
        \$query = "SELECT * FROM cyhub WHERE username='\$uname'";
        \$res = mysqli_query(\$conn, \$query);
        \$rows = @mysqli_fetch_array(\$res);
        if(\$rows){
                if( \$rows['role'] == "admin" ){
                        \$_SESSION['admin'] = 1;
                }else{
                        \$_SESSION['admin'] = 0;
                }
                \$_SESSION['flag'] = 1;
        }else{
                echo "<center>Invalid Creds.</center>";
        }
}
?>
<!DOCTYPE html>
<html>
        <head>
                <title>Login</title>
        </head>
        <body style="background-color: black;color:green;">
                <center>
                        <?php
                                if(@\$_SESSION['flag'] == 1){
                                        if(@\$_SESSION['admin'] == 1){
                                                echo "Hi admin :) <a href=index.php>home</a>";
                                        }else{
                                                echo "you're not admin :( <a href=index.php>home</a>";
                                        }
                                }
                        ?><br><br><br><br><br><br>
                <form method="POST">
                        <input type="text" style="width: 300px" name="uname" placeholder="Username" autocomplete="off"><br>
                        <input type="password" style="width: 300px" name="passwd" placeholder="Password" autocomplete="off"><br>
                        <input type="submit" value="Login">
                </form>
                </center>
        </body>
</html>
EOF

cat<<EOF >/root/dump.sql
-- MySQL dump 10.17  Distrib 10.3.24-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: cyhub
-- ------------------------------------------------------
-- Server version       10.3.24-MariaDB-2

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table \`cyhub\`
--

DROP TABLE IF EXISTS \`cyhub\`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE \`cyhub\` (
  \`username\` varchar(255) NOT NULL,
    \`password\` varchar(255) NOT NULL,
      \`email\` varchar(255) NOT NULL,
        \`role\` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table \`cyhub\`
--

LOCK TABLES \`cyhub\` WRITE;
/*!40000 ALTER TABLE \`cyhub\` DISABLE KEYS */;
INSERT INTO \`cyhub\` VALUES ('user','user_@_user','user@gmail.com','user'),('guest','guestguestguest','guest@gmail.com','user'),('dark','j0ny_I\$_aDm1N','jony@gmail.com','admin'),('joe','joe','joe@gmail.com','user');
/*!40000 ALTER TABLE \`cyhub\` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-10-20 23:40:24
EOF

mysql -u $user -p$passsword -Bse "create database cyhub;source /root/dump.sql;CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';GRANT ALL PRIVILEGES ON * . * TO 'user'@'localhost';"
